/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package menu;

import menu.dao.MySQLOpenHelper;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.util.Scanner;

public class AppTest {
    public void setUserInput(String simulatedUserInput) {
        simulatedUserInput += "\n";
        Scanner mockScanner = new Scanner(new ByteArrayInputStream(simulatedUserInput.getBytes()));
        App.setScanner(mockScanner);
    }
    @Test
    void welcome() {
        // Customer - exit system with no exist order - close the connection pool
        setUserInput("1\nexit");
        App.main(new String[] {});
        // Restart connection pool
        MySQLOpenHelper.getInstance().restartConnectionPool();

        // Customer - exit twice system with no exist order - close the connection pool
        setUserInput("1\nexit\nc\nexit");
        App.main(new String[] {});
        // Restart connection pool
        MySQLOpenHelper.getInstance().restartConnectionPool();

        // Customer - exit system with exist order - close the connection pool
        setUserInput("1\norder add 28\nexit\ny");
        App.main(new String[] {});
        // Restart connection pool
        MySQLOpenHelper.getInstance().restartConnectionPool();

        // Customer - exit twice system with exist order - close the connection pool
        setUserInput("1\nexit\nc\norder add 28\nexit\ny");
        App.main(new String[] {});
        // Restart connection pool
        MySQLOpenHelper.getInstance().restartConnectionPool();

        // Customer - enter system with invalid input (null) - close the connection pool
        setUserInput("1");
        App.main(new String[] {});

        // Customer - enter system with invalid input (invalid) - close the connection pool
        setUserInput("invalid\n1");
        App.main(new String[] {});

        // Admin - exit system with no exist order - close the connection pool
        setUserInput("2\nadmin\n111111\nexit\ny");
        App.main(new String[] {});
        // Restart connection pool
        MySQLOpenHelper.getInstance().restartConnectionPool();
    }
}
